# Generated by Django 5.1.4 on 2025-01-12 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.DateTimeField()),
            ],
        ),
    ]
