# Generated by Django 5.1.4 on 2025-01-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='created_by',
            new_name='modified_by',
        ),
    ]
