# Generated by Django 5.1.5 on 2025-01-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_rename_created_by_documentation_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='modified_by',
            field=models.DateTimeField(blank=True),
        ),
    ]
